# Generated by Django 5.1.4 on 2024-12-25 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_number', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('train_types', models.CharField(choices=[('EXPRESS', 'Express Train'), ('PASSENGER', 'Passenger Train'), ('FREIGHT', 'Freight Train')], max_length=20)),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')])),
                ('platform', models.IntegerField()),
                ('scheduled_arrival', models.DateTimeField()),
                ('scheduled_departure', models.DateTimeField()),
                ('actual_arrival', models.DateTimeField(blank=True, null=True)),
                ('actual_departure', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('ARRIVING', 'Arriving'), ('AT_STATION', 'At Station'), ('DEPARTED', 'Departed'), ('DELAYED', 'Delayed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('delay_minutes', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['scheduled_arrival'],
            },
        ),
        migrations.CreateModel(
            name='TrainStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('platforms', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='TrainLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(max_length=50)),
                ('description', models.TimeField()),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train_scheduler.train')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='train',
            name='current_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_trains', to='train_scheduler.trainstation'),
        ),
    ]
